name: dialect # you probably want to 'snapcraft register <name>'
adopt-info: dialect
base: core22 # the base snap is the execution environment for this snap
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+
compression: lzo
source-code: https://github.com/dialect-app/dialect
grade: stable
issues: https://github.com/soumyaDghosh/dialect-snap/issues
website: https://github.com/soumyaDghosh/dialect-snap
type: app
contact: soumyadeepghosh2004@zohomail.in

architectures:
  - build-on: amd64
  - build-on: arm64

#For GtkApplication registration
slots:
  dialect:
    bus: session
    interface: dbus
    name: app.drey.Dialect

parts:
  python-deps:
    source: .
    plugin: python
    python-packages:
      - gTTs==2.2.3
      - beautifulsoup4==4.12.2
    prime:
      - -bin
      - -include
      - -lib64
    organize:
      lib/python3.10/site-packages: usr/lib/python3.10/dist-packages

  dialect:
    plugin: meson
    source: https://github.com/dialect-app/dialect.git
    source-tag: '2.5.0'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/dialect/current/usr
    build-snaps:
      - blueprint-compiler
    build-packages:
      - libgstreamer1.0-dev
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/dialect.patch
    override-build: |
      craftctl default    
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/dialect/current/usr/bin/dialect
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/dialect/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    organize:
      snap/dialect/current: .
    parse-info: [usr/share/metainfo/app.drey.Dialect.metainfo.xml]
    prime:
      - -snap/dialect
      - -usr/share/gnome-shell

  deps:
    plugin: nil
    stage-packages:
      - gir1.2-gstreamer-1.0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/Gst-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstBase-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstCheck-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstController-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstNet-1.0.typelib

apps:
  dialect:
    command: usr/bin/dialect
    extensions: [gnome]
    common-id: app.drey.Dialect
    desktop: usr/share/applications/app.drey.Dialect.desktop
    environment:
      # WORKAROUND: Add python modules in Snap to search path
      PYTHONPATH: ${SNAP}/usr/lib/python3.10/dist-packages:$PYTHONPATH
    plugs:
      - network-status
      - audio-playback
      - network
