name: dialect # you probably want to 'snapcraft register <name>'
adopt-info: dialect
base: core22 # the base snap is the execution environment for this snap
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+
compression: lzo
source-code: https://github.com/dialect-app/dialect
grade: stable
issues: https://github.com/soumyaDghosh/dialect-snap/issues
website: https://github.com/soumyaDghosh/dialect-snap
type: app
contact: soumyadeepghosh2004@zohomail.in

architectures:
  - build-on: amd64
  - build-on: arm64

#For GtkApplication registration
slots:
  dialect:
    bus: session
    interface: dbus
    name: app.drey.Dialect

parts:
  dialect:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/dialect-app/dialect.git
    source-tag: '2.1.1'
    meson-parameters:
      - --prefix=/snap/dialect/current/usr
    build-packages:
      - blueprint-compiler
      - libgstreamer1.0-dev
      - libpython3.10-dev
      - patchelf
    stage-packages:
      - gir1.2-gstreamer-1.0
    override-build: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr gTTs     
      pip install --prefix=$CRAFT_PART_INSTALL/usr dbus-python 
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/dialect/current/usr/bin/dialect
      sed -e '1c#!/usr/bin/python3' -i $CRAFT_PART_INSTALL/usr/local/bin/*
    organize:
      # WORKAROUND: Move files from fake installation location to actual target
      snap/dialect/current/usr: usr
      usr/local: usr
    parse-info: [usr/share/metainfo/app.drey.Dialect.metainfo.xml]
    prime:
      - -snap/dialect
      - -usr/include
      - -usr/bin/normalizer
      - -usr/bin/gtts-cli
      - -usr/share/doc
    

  cleanup:
    after:  # Make this part run last; list all your other parts here
      - dialect
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  dialect:
    command: usr/bin/dialect
    extensions: [gnome]
    common-id: app.drey.Dialect
    desktop: usr/share/applications/app.drey.Dialect.desktop
    environment:
      # WORKAROUND: Add python modules in Snap to search path
      PYTHONPATH: ${SNAP}/usr/lib/python3.10/dist-packages:$PYTHONPATH
    plugs:
      - network-status
      - audio-playback
      - network
